# $Id$
CFLAGS=-O2 -std=c99 -Wall -Wextra -Wpedantic # try -O3 for fun...

ALL=minunit_example sizeof bitsets loweror options microbench # get_set_progname #fsize #args

all: $(ALL)

clean:
	rm -rf *.o $(ALL)
